const schema = (dbName) => [
  `CREATE TABLE IF NOT EXISTS ${dbName}.user_role_table (id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) UNIQUE, password TEXT, user_title TEXT, database_id TEXT, sale_permission BOOLEAN DEFAULT FALSE, parties_permission BOOLEAN DEFAULT FALSE, purchase_permission BOOLEAN DEFAULT FALSE, product_permission BOOLEAN DEFAULT FALSE, profile_edit_permission BOOLEAN DEFAULT FALSE, add_expense_permission BOOLEAN DEFAULT FALSE, loss_profit_permission BOOLEAN DEFAULT FALSE, due_list_permission BOOLEAN DEFAULT FALSE, stock_permission BOOLEAN DEFAULT FALSE, reports_permission BOOLEAN DEFAULT FALSE, sales_list_permission BOOLEAN DEFAULT FALSE, purchase_list_permission BOOLEAN DEFAULT FALSE, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.products_table (id INT AUTO_INCREMENT PRIMARY KEY, product_name TEXT, product_category TEXT, size TEXT, color TEXT, weight TEXT, capacity TEXT, type TEXT, brand_name TEXT, product_code VARCHAR(255) UNIQUE, product_stock TEXT, product_unit TEXT, product_sale_price TEXT, product_purchase_price TEXT, product_discount TEXT, product_whole_sale_price TEXT, product_dealer_price TEXT, product_manufacturer TEXT, product_picture LONGTEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.sales_table (id INT AUTO_INCREMENT PRIMARY KEY, customer_name TEXT, customer_phone TEXT, customer_type TEXT, sales_invoice_number VARCHAR(255) UNIQUE, purchase_date TEXT, total_amount DOUBLE, due_amount DOUBLE, return_amount DOUBLE, vat DOUBLE, discount_amount DOUBLE, loss_profit DOUBLE, total_quantity INT, is_paid BOOLEAN, payment_type TEXT, seller_name TEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, loyalty_points_earned DOUBLE DEFAULT 0, loyalty_points_redeemed DOUBLE DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.sale_items_table (id INT AUTO_INCREMENT PRIMARY KEY, invoice_number TEXT, product_id TEXT, product_name TEXT, product_brand_name TEXT, unit_price DOUBLE, sub_total DOUBLE, product_purchase_price DOUBLE, quantity INT, stock INT, product_details_json TEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.personal_information_table (id INT AUTO_INCREMENT PRIMARY KEY, phone_number TEXT, company_name TEXT, picture_url LONGTEXT, business_category TEXT, language TEXT, country_name TEXT, invoice_counter INT DEFAULT 1, shop_opening_balance INT DEFAULT 0, remaining_shop_balance INT DEFAULT 0, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.customer_table (id INT AUTO_INCREMENT PRIMARY KEY, customer_name TEXT, phone_number VARCHAR(255) UNIQUE, type TEXT, profile_picture LONGTEXT, email_address TEXT, customer_address TEXT, due_amount DOUBLE DEFAULT 0, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, loyalty_points DOUBLE DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.categories_table (id INT AUTO_INCREMENT PRIMARY KEY, category_name TEXT, category_description TEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.brands_table (id INT AUTO_INCREMENT PRIMARY KEY, brand_name TEXT, brand_description TEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.units_table (id INT AUTO_INCREMENT PRIMARY KEY, unit_name TEXT, unit_description TEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.expense_category_table (id INT AUTO_INCREMENT PRIMARY KEY, category_name TEXT, description TEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.expense_table (id INT AUTO_INCREMENT PRIMARY KEY, expense_date TEXT, category TEXT, expanse_for TEXT, payment_type TEXT, account TEXT, amount TEXT, reference_no TEXT, note TEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.purchase_table (id INT AUTO_INCREMENT PRIMARY KEY, customer_name TEXT, customer_phone TEXT, customer_type TEXT, invoice_number VARCHAR(255) UNIQUE, purchase_date TEXT, total_amount DOUBLE, due_amount DOUBLE, return_amount DOUBLE, discount_amount DOUBLE, is_paid BOOLEAN, payment_type TEXT, seller_name TEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.purchase_items_table (id INT AUTO_INCREMENT PRIMARY KEY, invoice_number TEXT, product_id TEXT, product_name TEXT, product_code TEXT, purchase_price DOUBLE, sub_total DOUBLE, quantity INT, product_details_json TEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.business_settings_table (id INT AUTO_INCREMENT PRIMARY KEY, currency_name TEXT, currency_symbol TEXT, company_name TEXT, company_phone TEXT, company_address TEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, is_loyalty_enabled BOOLEAN DEFAULT FALSE, loyalty_point_value DOUBLE DEFAULT 1.0, loyalty_point_earn_rate DOUBLE DEFAULT 100.0)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.subscription_table (id INT AUTO_INCREMENT PRIMARY KEY, subscription_name TEXT, sale_number INT DEFAULT 0, purchase_number INT DEFAULT 0, products INT DEFAULT 0, parties_number INT DEFAULT 0, due_number INT DEFAULT 0, duration INT DEFAULT 0, subscription_date TEXT, expire_date TEXT, total_sale_number INT DEFAULT 0, total_purchase_number INT DEFAULT 0, total_products INT DEFAULT 0, total_parties_number INT DEFAULT 0, total_due_number INT DEFAULT 0, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.home_page_image_table (id INT AUTO_INCREMENT PRIMARY KEY, image_url LONGTEXT, is_asset BOOLEAN DEFAULT FALSE, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.subscription_plan_table (id INT AUTO_INCREMENT PRIMARY KEY, subscription_name TEXT, sale_number INT, purchase_number INT, parties_number INT, due_number INT, duration INT, products INT, subscription_price INT, offer_price INT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.receipt_settings_table (id INT AUTO_INCREMENT PRIMARY KEY, company_name TEXT, address TEXT, phone TEXT, logo_path LONGTEXT, header_text TEXT, footer_text TEXT, layout_order TEXT, show_logo BOOLEAN DEFAULT TRUE, show_address BOOLEAN DEFAULT TRUE, show_phone BOOLEAN DEFAULT TRUE, show_bill_no BOOLEAN DEFAULT TRUE, show_table_no BOOLEAN DEFAULT TRUE, show_cashier BOOLEAN DEFAULT TRUE, show_date BOOLEAN DEFAULT TRUE, font_size INT DEFAULT 10, auto_print BOOLEAN DEFAULT FALSE, default_printer_name TEXT, paper_size VARCHAR(255) DEFAULT '58mm', margin_top DOUBLE DEFAULT 0.0, margin_bottom DOUBLE DEFAULT 0.0, margin_left DOUBLE DEFAULT 0.0, margin_right DOUBLE DEFAULT 0.0, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.due_transaction_table (id INT AUTO_INCREMENT PRIMARY KEY, customer_name TEXT, customer_phone TEXT, customer_type TEXT, invoice_number VARCHAR(255), purchase_date VARCHAR(100), total_due DOUBLE, due_amount_after_pay DOUBLE, pay_due_amount DOUBLE, is_paid BOOLEAN, payment_type TEXT, seller_name TEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT unique_due_payment UNIQUE (invoice_number, purchase_date, pay_due_amount))`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.purchase_return_table (id INT AUTO_INCREMENT PRIMARY KEY, customer_name TEXT, customer_phone TEXT, customer_type TEXT, invoice_number VARCHAR(255) UNIQUE, return_date TEXT, total_amount DOUBLE, due_amount DOUBLE, refund_amount DOUBLE, payment_type TEXT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ${dbName}.purchase_return_items_table (id INT AUTO_INCREMENT PRIMARY KEY, invoice_number TEXT, product_name TEXT, product_code TEXT, purchase_price DOUBLE, sub_total DOUBLE, quantity INT, is_synced BOOLEAN DEFAULT FALSE, is_deleted BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`
];

module.exports = { schema };
